{% set name = "irrep" %}
{% set version = "2.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/irrep-{{ version }}.tar.gz
  sha256: 6107cdd70c98f901986deed158d2904d1041d94ddf5255d2f365833c3e54d69e

build:
  entry_points:
    - irrep = irrep.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - h5py
    - packaging
    - python >={{ python_min }}
    - numpy
    - scipy >=1.0
    - spglib >=2.5.0
    - lazy-property
    - click
    - monty
    - ruamel.yaml
    - irreptables >=2.0
    - fortio

test:
  imports:
    - irrep
  commands:
    - pip check
    - irrep --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/stepan-tsirkin/irrep
  summary: A tool to get symmetry proberties of ab-initio wavefunctions, irreduible representations and more.
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
