{% set name = "irrep" %}
{% set version = "1.11.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/irrep-{{ version }}.tar.gz
  sha256: 3d5a82f3d58b7cc01005d2372b5b360c40f3cf2ffc30feecdaf64feb951615dc

build:
  entry_points:
    - irrep = irrep.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - h5py
    - packaging
    - python >={{ python_min }}
    - numpy
    - scipy >=1.0
    - spglib >=1.14
    - lazy-property
    - click
    - monty
    - ruamel.yaml
    - irreptables >=1.1.0
    - fortio

test:
  imports:
    - irrep
  commands:
    - pip check
    - irrep --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/stepan-tsirkin/irrep
  summary: A tool to get symmetry proberties of ab-initio wavefunctions, irreduible representations and more.
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
