{% set name = "irrep" %}
{% set version = "1.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/irrep-{{ version }}.tar.gz
  sha256: 2ca3b152abde7bc7d013cbc544994377683ddff61b2b05076ff0ff4525323df0

build:
  entry_points:
    - irrep = irrep.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - h5py
    - packaging
    - python >=3.6
    - numpy
    - scipy >=1.0
    - spglib >=1.14
    - lazy-property
    - click
    - monty
    - ruamel.yaml
    - irreptables >=1.1.0
    - fortio

test:
  imports:
    - irrep
  commands:
    - pip check
    - irrep --help
  requires:
    - pip

about:
  home: https://github.com/stepan-tsirkin/irrep
  summary: A tool to get symmetry proberties of ab-initio wavefunctions, irreduible representations and more.
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
